fix deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,33 +7,34 @@ on:
       - master
 
 jobs:
-  build-and-push:
+  build-and-deploy:
     runs-on: ubuntu-latest
 
     steps:
       # Checkout Repository
-      - name: Check Out Repo
+      - name: Checkout Repo
         uses: actions/checkout@v4
 
       # Login to Docker Hub
-      - name: Log in to Docker Hub
+      - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       # Build and Push Docker Image
-      - name: Build and Push Docker image
+      - name: Build and Push Docker Image
         uses: docker/build-push-action@v6
         with:
           context: .
           push: true
           tags: vivek60631/tomato:latest
 
-      # Verify Pushed Image
-      - name: Verify Pushed Image
+      # Verify Image
+      - name: Verify Docker Image
         run: docker pull vivek60631/tomato:latest
 
+      # Deploy to EC2
       - name: Deploy to EC2
         uses: appleboy/ssh-action@master
         with:
@@ -41,12 +42,26 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
+            # Install Docker if not installed
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              sudo apt update
+              sudo apt install docker.io -y
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            fi
+
+            # Pull latest image
             sudo docker pull vivek60631/tomato:latest
 
+            # Stop and remove old container
             sudo docker stop food-app || true
             sudo docker rm food-app || true
 
+            # Run new container
             sudo docker run -d \
               --name food-app \
               -p 3000:3000 \
+              --restart always \
               vivek60631/tomato:latest
